type Query {
	ping: String!
	subdivisions(filters: SubdivisionFilters): [Area!]!
}

type Area {
	id: ID!
	name: String!
	unit: String!
	level: Int!
}

input SubdivisionFilters {
	parentId: ID
	level: Int
	unit: String
}